### ISSUE TITLE
不支持最新版UI

### ISSUE THREAD

**Issue by zhouxianjun** [jadepeng/idea-rainbow-fart#2]
最新版idea安装不了

**Comment by chenhaoxiang** [comment]
+1

**Comment by chenhaoxiang** [comment]
2020.1.1

**Comment by NEETLee** [comment]
IDE信息：
PhpStorm 2020.1
Build #PS-201.6668.153, built on April 13, 2020
Licensed to lihan

Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1778M
Cores: 4
Registry: run.processes.with.pty=TRUE, documentation.show.toolbar=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Key Promoter X, SnakeYAML plugin, YAML/Ansible support, com.chrisrm.idea.MaterialThemeUI, com.intellij.zh, com.mallowigi, mobi.hsz.idea.gitignore, io.zhile.crack.jetbrains.agent, ru.adelf.idea.dotenv, de.espend.idea.php.annotation, fr.adrienbrault.idea.symfony2plugin, lt.martynassateika.idea.codeigniter, org.psliwa.idea.composer, some.awesome

异常信息：
`java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
	at com.github.jadepeng.rainbowfart.Context.readVoicePackageJson(Context.java:112)
	at com.github.jadepeng.rainbowfart.Context.loadConfig(Context.java:126)
	at com.github.jadepeng.rainbowfart.PluginStarter.runActivity(PluginStarter.java:16)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:289)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$null$3(StartupManagerImpl.java:233)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:426)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:418)
	at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:884)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils PluginClassLoader[com.github.jadepeng.rainbowfart, 1.0.3] com.intellij.ide.plugins.cl.PluginClassLoader@16647bb3
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:115)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 35 more`

**Comment by jadepeng** [comment]
下载 https://github.com/jadepeng/idea-rainbow-fart/releases/tag/1.0.4 试试
我测试，最新版本的2020.1.2 可用

**Comment by tiannoyi** [comment]
2020.1.1用不了
